import "@/app/globals.css";

import { Inter } from "next/font/google";
import Header from "@/components/header";
import Menu from "@/components/menu";
import { Toaster } from "sonner";

export const metadata = {
  title: "Restaurante Joselu",
  description: "Generated by create next app",
  manifest: "/pwa/manifest.json",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={`antialiased min-h-screen bg-[url(/images/fondo.jpg)] bg-cover bg-bottom-left bg-fixed`}
      >
        <Header />
        <Menu />
        <div className="pt-32">{children}</div>
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
