import "@/app/globals.css";

import { Inter } from "next/font/google";
import Header from "@/components/header";

export const metadata = {
  title: "Pizzería",
  description: "Generated by create next app",
  manifest: "/pwa/manifest.json",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={`antialiased min-h-screen bg-[url(/images/fondo2.jpg)] bg-cover bg-bottom-left bg-fixed`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
